story4app/urls.py
from django.urls import path
from . import views

app_name = "story4app"

urlpatterns = [
	path('', views.home, name="home"),
	path('playlist', views.playlist, name="playlist"),
	path('signup', views.signup, name="signup")
]

story4pro/urls.py
from django.contrib import admin
from django.conf.urls import url, include 
from django.urls import path, include
from story4app.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('', include('story4app.urls')),
    path('', include('story5app.urls')),
]

story5app/urls.py
from django.urls import path
from . import views

app_name = "story5app"

urlpatterns = [
	path('portfolioform', views.portfolioform, name="portfolioform"),
	path('portfolio', views.portfolio, name="portfolio"),
	path('deleteportfolio', views.delete_portfolio, name="delete_portfolio")
]

story4app/models.py
from django.db import models

# Create your models here.

story5app/models.py
from django.db import models

# Create your models here.

class Portfolio(models.Model):
    title = models.CharField(max_length=30)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    desc = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    category = models.CharField(max_length=30)

story5app/forms.py
from django import forms
from .models import Portfolio

class PortfolioForm(forms.Form):
	status_attrs = {
	    'type':'date',
	    'placeholder':'YYYY-MM-DD',
	}	
	title = forms.CharField(label="Judul")
	date_start = forms.DateField(label="Tanggal Mulai", widget=forms.DateInput(attrs=status_attrs))
	date_end = forms.DateField(label="Tanggal Selesai", widget=forms.DateInput(attrs=status_attrs))
	desc = forms.CharField(label="Deskripsi Singkat Proyek")
	place = forms.CharField(label="Tempat")
	category = forms.CharField(label="Kategori Proyek")

story4app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, "story3.html", {})

def playlist(request):
    return render(request, "story3_playlist.html", {})

def signup(request):
    return render(request, "story3_signup.html", {})

story5app/views.py
from django.shortcuts import render, redirect
from .forms import PortfolioForm
from .models import Portfolio

# Create your views here.

def portfolio(request):
    response = {}
    portfolios = Portfolio.objects.all().values()
    response = {
        "portfolios" : portfolios
    }
    return render(request, 'story5_portfoliolist.html', response)

def portfolioform(request):
    form = PortfolioForm(request.POST or None)
    response = {}
    if(request.method == "POST"):
        if (form.is_valid()):
            title = request.POST.get("title")
            date_start = request.POST.get("date_start")
            date_end = request.POST.get("date_end")
            desc = request.POST.get("desc")
            place = request.POST.get("place")
            category = request.POST.get("category")
            Portfolio.objects.create(title=title, date_start=date_start, date_end=date_end, desc=desc, place=place, category=category)
            return redirect('/portfolio')
        else:
            return render(request, 'story5_portfolioform.html', response)
    else:
        response['form'] = form
        return render(request, 'story5_portfolioform.html', response)

def delete_portfolio(request):
    Portfolio.objects.filter().delete()
    return redirect('/portfolio')

story4app/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>

  </head>

  <body>
      {% include "story3_navbar.html" %}

      {% block content %}
      {% endblock %}

      {% include "story3_footer.html" %}
</body>
</html>

story4app/templates/story3.html
{% extends 'base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>

  <title>Khameela's Profile</title>
  </head>

  <body>
  	<div class = "container webnya">
      <div class="row">
        <div class="col-sm-4 image overlay">
          <img class="profile" src="http://mela-ppw.herokuapp.com/foto.png">
          <div class="judul">Khameela Rahmah.</div>
          <div class="little-desc">
            <ul style="list-style-type:none;">
              <li>19 yo.</li>
              <li>Student.</li>
              <li>Scorpion.</li>
              <li>INFP.</li>
            </ul> 
          </div>
        </div>
        <div class="col-sm-8">
          <div class="row">
          <div class="col-sm-11">
            <br>
            <div class="judul-desc">A little more about myself</div>
            <div class="desc">Her friends and family called her Mela. Was born in Jakarta on October 26, 1999. The 2nd child in the family. Currently studying at Fasilkom Universitas Indonesia. Like Japanese Vibes and wish someday could go there. Like listening to good musics and watch good movies.</div>
          </div>
          <div class="col-sm-11">
            <br>
            <div class = "judul-desc">Experiences</div>
            <div class = "desc">
              <dl>
                <dt>Biro Media BEM Fasilkom UI</dt>
                <dt>Divisi Dekorasi CGT 2018</dt>
                <dt>Divisi Press COMPFEST X</dt>
                <dt>Divisi HPK PMB 2018</dt>
                <dt>Divisi Kreatif Wisgan 2019 </dt>
              </dl> 
            </div>
          </div>
            <div class="col-sm">
              <div class="judul-desc">Educations</div>
              <div class="desc">
                <dl>
                  <dt>Universitas Indonesia</dt>
                  <dt>SMAN 39 Jakarta</dt>
                  <dt>SMPN 49 Jakarta</dt>
                  <dt>SDN Dukuh 09 Pagi</dt>
                </dl> 
              </div>
            </div>
              <div class="col-sm">
              	<div class="container">
              		<div class="judul-desc">Skills</div>
              		<div class="desc">Digital Design</div>
              		<div class="progress">
              			<div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%; background-color: #0E1C36;">80%</div>
              		</div>
              		<br>
              		<div class="desc">Digital Writing</div>
              		<div class="progress">
              			<div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%; background-color: #0E1C36;">70%</div>
              		</div>
              	</div>
              </div>
              <div class="col-sm-11 col-centered">
              	<br>
          		<a href="https://twitter.com/melarhmh"> <img alt="to twitter" src="https://saltncookies.files.wordpress.com/2019/02/twitter-logo-button.png?w=400&h=401&zoom=2" style="width: 50px; height: 50px"></a>
              	<a href="mailto:khameelarahmah@example.com"> <img alt="send an email" src="https://saltncookies.files.wordpress.com/2019/02/closed-envelope-circle.png?w=401&h=401&crop=1&zoom=2" style="width: 50px; height: 50px"></a>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}
</body>
</html>

story4app/templates/story3_footer.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>
  </head>

  <body>
    <!-- Footer -->
    <footer class="page-footer font-small" style="color: #0E1C36">
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
          <a href="https://web-mela.herokuapp.com" style="color: #3D348B"> Khameela Rahmah</a>
          <br>
          {{ date }}
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
</body>
</html>

story4app/templates/story3_navbar.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" style="border-color: #FFEDE1">
        <span class="navbar-toggler-icon"></span>
      </button> 
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}" style="color: #FFEDE1">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="playlist"style="color: #FFEDE1">Playlist</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" style="color: #FFEDE1">
                Portfolio
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="portfolioform" style="color: #0E1C36">Create</a>
                <a class="dropdown-item" href="portfolio" style="color: #0E1C36">List</a>
              </div>
            </li>   
            <li class="nav-item">
              <a class="nav-link" href="signup" style="color: #FFEDE1">Sign Up</a>
            </li>
          </ul>
        </div>  
      </nav>
</body>
</html>

story4app/templates/story3_playlist.html
{% extends 'base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>

  <title>Khameela's Playlist</title>
  </head>

  <body>
    <div class = "container webnya">
      <div class="row">
        <div class="col-sm-4 image overlay">
          <div class="judul-pl">Playlist.
          </div>
          <div class="little-pl">Mela loves to listening to good musics. Here are some of her reccomendations.
          </div>
        </div>
        <div class="col-sm-8">
          <div class="row">
          <div class="col-sm"> 
            <br>
            <div class="song-title">Finding Hope - More & More</div>
            <div class="song-desc">If you want to hear a very easy listening acoustic song, then this song is for you. It's very rich with the harmonisation of the acoustic guitar that you'll hear throughout the song. Lyric-wise is very simple yet very straightforward. Such a gem.</div>
            <br>
            <div class="link-song">
              <a href="https://www.youtube.com/watch?v=ZSSyl6wqWYM">Listen to it on YouTube.</a>
            </div>
            <br>
            <div class="song-title">Jimin of BTS - 약속 (Promise)</div>
            <div class="song-desc">Another acoustic song but this time from the singer that I'm really familiar of. Jimin of BTS released this song on December last year. It's a really sweet song with such a sweet meaning. The lyrics tell you to 'promise me you don't throw yourself away even if you're feel all alone, you still have me' kind of thing. Not to mention Jimin's sweet voice made this song even more complete.</div>
            <br>
            <div class="link-song">
              <a href="https://soundcloud.com/bangtan/firstjiminpresent">Listen to it on Soundcloud.</a>
            </div>
            <br>
            <div class="song-title">Rita Ora - Velvet Rope</div>
            <div class="song-desc">I've just discovered the song! This song came from her 2018 album, Phoenix, alongside with her hits such as 'Anywhere' and 'Let You Love Me'. Unlike those other two songs, Velvet Rope have a very chill tune. Really worth to listen.</div>
            <br>
            <div class="link-song">
              <a href="https://open.spotify.com/track/5S5xmV52bqwZ8bkBCyAAdy?si=kKRBQzt_Qz6ys822UHm5JA">Listen to it on Spotify.</a>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
    
    {% endblock %}
  </body>
</html>

story4app/templates/story3_signup.html
{% extends 'base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>

  <title>Be a Regular Member</title>
  </head>

  <body>
    <div class = "container webnya">
      <div class="row">
        <div class="col-sm-4 image overlay">
          <div class="judul-signup">Sign Yourself Up.</div>
          <div class="little-signup">Connect to Mela's website as a regular member.</div>
        </div>
        <div class="col-sm-8">
          <div class="row">
          <div class="col-sm"> 
            <br><br><br><br><br>
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="email@example.com">
                <small id="emailHelp" class="form-text text-muted">I'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="exampleInputUsername1">Username</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                  <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Username">
                </div>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="wrapper">
                <button type="submit" class="btn btn-primary">SIGN ME UP</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

story5app/templates/story5_portfolioform.html
{% extends 'base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>

  <title>Create Portfolio</title>
  </head>

  <body>
    <div class = "container webnya">
      <div class="row">
        <div class="col-sm-4 image overlay">
          <div class="judul-signup">Create Portfolio.</div>
          <div class="little-signup">Submit portfolio through form.</div>
        </div>
        <div class="col-sm-8">
          <div class="row">
          <div class="col-sm"> 
            <br><br><br><br><br>
            <form action="#" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <p>{{ field.label_tag }} {{ field }}</p>
                {% endfor %}
                <button type="submit" class="btn btn-primary">SUBMIT</button>
            </form>
          </div>
        </div>
      </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

story5app/templates/story5_portfoliolist.html
{% extends 'base.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  {% load static %}
  <link href="{% static 'style_story3.css' %}" type="text/css" rel="stylesheet"/>

  <title>Portfolio List</title>
  </head>

  <body>
    <div class = "container webnya">
      <div class="row">
        <div class="col-sm-4 image overlay">
          <div class="judul-signup" style="left: 20%">Portfolio List.</div>
          <div class="little-signup">See portfolio list.</div>
        </div>
        <div class="col-sm-8">
          <div class="row">
          <div class="col-sm"> 
            <br><br><br><br><br>
            
            <table style="width:100%">
                {% if portfolios %}
                    <tr>
                        <th>Judul</th>
                        <th>Tanggal Mulai - Tanggal Selesai</th>
                        <th>Deskripsi Singkat Proyek</th>
                        <th>Tempat</th>
                        <th>Kategori Proyek</th>
                    </tr>
                    {% for portfolio in portfolios %}
                        <tr>
                            <td>{{ portfolio.title }}</td>
                            <td>{{ portfolio.date_start }} - {{ portfolio.date_end }}</td> 
                            <td>{{ portfolio.desc }}</td>
                            <td>{{ portfolio.place }}</td>
                            <td>{{ portfolio.category }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <h5>Belum ada Portfolio</h5> 
                {% endif %}
            </table>

          <div class="col-sm-11 col-centered">
            <a href="{% url 'story5app:delete_portfolio' %}" class="btn btn-danger" role="button" aria-pressed="true">DELETE LIST</a>
          </div>

          </div>
        </div>
      </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>